version: "3.7"
services:
  frontend:
    image: konnyaku256/heyson-frontend:latest
    ports:
      - 8080:80
    restart: always
  backend:
    image: konnyaku256/heyson-backend:latest
    ports:
      - 3000:3000
    devices:
      - "/dev/snd"
    restart: always
